package game.model;

public enum CardSet {
    SPADE_K("K스페이드"),
    SPADE_Q("Q스페이드"),
    SPADE_J("J스페이드"),
    SPADE_10("10스페이드"),
    SPADE_9("9스페이드"),
    SPADE_8("8스페이드"),
    SPADE_7("7스페이드"),
    SPADE_6("6스페이드"),
    SPADE_5("5스페이드"),
    SPADE_4("4스페이드"),
    SPADE_3("3스페이드"),
    SPADE_2("2스페이드"),
    SPADE_A("A스페이드"),
    HEART_K("K하트"),
    HEART_Q("Q하트"),
    HEART_J("J하트"),
    HEART_10("10하트"),
    HEART_9("9하트"),
    HEART_8("8하트"),
    HEART_7("7하트"),
    HEART_6("6하트"),
    HEART_5("5하트"),
    HEART_4("4하트"),
    HEART_3("3하트"),
    HEART_2("2하트"),
    HEART_A("A하트"),
    DIAMOND_K("K다이아몬드"),
    DIAMOND_Q("Q다이아몬드"),
    DIAMOND_J("J다이아몬드"),
    DIAMOND_10("10다이아몬드"),
    DIAMOND_9("9다이아몬드"),
    DIAMOND_8("8다이아몬드"),
    DIAMOND_7("7다이아몬드"),
    DIAMOND_6("6다이아몬드"),
    DIAMOND_5("5다이아몬드"),
    DIAMOND_4("4다이아몬드"),
    DIAMOND_3("3다이아몬드"),
    DIAMOND_2("2다이아몬드"),
    DIAMOND_A("A다이아몬드"),
    CLOVER_K("K클로버"),
    CLOVER_Q("Q클로버"),
    CLOVER_J("J클로버"),
    CLOVER_10("10클로버"),
    CLOVER_9("9클로버"),
    CLOVER_8("8클로버"),
    CLOVER_7("7클로버"),
    CLOVER_6("6클로버"),
    CLOVER_5("5클로버"),
    CLOVER_4("4클로버"),
    CLOVER_3("3클로버"),
    CLOVER_2("2클로버"),
    CLOVER_A("A클로버");



    CardSet(String cardName) {

    }
}
